services:

  wordpress:
    container_name: vuln-wp-really-simple-security
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1337:80
    environment:
      WORDPRESS_DEBUG: 1
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    container_name: vuln-wp-really-simple-security-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpress_really_simple_security_db:/var/lib/mysql

volumes:
  wordpress_really_simple_security_db:
